# Game mode mappings — exactly as in original formatter.py
GAME_MODE_NAMES = {
    0: "Unknown",
    1: "All Pick",
    2: "Captains Mode",
    3: "Random Draft",
    4: "Single Draft",
    5: "All Random",
    6: "Intro",
    7: "Diretide",
    8: "Reverse Captains Mode",
    9: "Greeviling",
    10: "Tutorial",
    11: "Mid Only",
    12: "Least Played",
    13: "Limited Heroes",
    14: "Compendium Matchmaking",
    15: "Custom",
    16: "Captains Draft",
    17: "Balanced Draft",
    18: "Ability Draft",
    19: "Event",
    20: "All Random Deathmatch",
    21: "1v1 Mid",
    22: "All Draft",
    23: "Turbo",
    24: "Mutation",
}

RAW_MODE_LABELS = {
    "all_pick": "All Pick",
    "captains_mode": "Captains Mode",
    "random_draft": "Random Draft",
    "single_draft": "Single Draft",
    "all_random": "All Random",
    "intro": "Intro",
    "diretide": "Diretide",
    "reverse_captains_mode": "Reverse Captains Mode",
    "greeviling": "Greeviling",
    "tutorial": "Tutorial",
    "mid_only": "Mid Only",
    "least_played": "Least Played",
    "limited_heroes": "Limited Heroes",
    "compendium_matchmaking": "Compendium Matchmaking",
    "custom": "Custom",
    "captains_draft": "Captains Draft",
    "balanced_draft": "Balanced Draft",
    "ability_draft": "Ability Draft",
    "event": "Event",
    "all_random_death_match": "All Random Deathmatch",
    "1v1_mid": "1v1 Mid",
    "all_draft": "All Draft",
    "turbo": "Turbo",
    "mutation": "Mutation",
}
