name: Debug Gist Access

on:
  workflow_dispatch:        # Run manually from GitHub Actions tab

jobs:
  run-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests package
        run: pip install requests

      - name: Run Gist Debug Script
        run: python debug-gist.py
